
-- SCHEMA
create table if not exists profiles ( user_id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz default now() );
create table if not exists categories ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, name text not null, type text not null check (type in ('receita','despesa')), color text, archived boolean default false, created_at timestamptz default now() );
create table if not exists fixed_bills ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, name text not null, amount numeric(12,2) not null, due_day int check (due_day between 1 and 31), category_id uuid references categories(id), active boolean default true, created_at timestamptz default now() );
create table if not exists cards ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade, alias text not null, limit_amount numeric(12,2), closing_day int check (closing_day between 1 and 31) not null, due_day int check (due_day between 1 and 31) not null, brand text, created_at timestamptz default now() );
create table if not exists card_purchases ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade default auth.uid(), card_id uuid references cards(id) on delete cascade, description text not null, category_id uuid references categories(id), amount numeric(12,2) not null, purchase_date date not null, installments_total int default 1, installment_number int default 1, responsible text not null check (responsible in ('Gabriela','Caue','Ambos')), invoice_month date not null, created_at timestamptz default now() );
create table if not exists cash_flows ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade default auth.uid(), type text not null check (type in ('receita','despesa')), method text not null check (method in ('debito_pix','outro')), category_id uuid references categories(id), description text, amount numeric(12,2) not null, competence_date date not null, paid_at date, responsible text not null check (responsible in ('Gabriela','Caue','Ambos')), receipt_url text, created_at timestamptz default now() );
create table if not exists savings_moves ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade default auth.uid(), type text not null check (type in ('aporte','retirada')), amount numeric(12,2) not null, date date not null, note text, created_at timestamptz default now() );
create table if not exists savings_goals ( id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete cascade default auth.uid(), name text not null, target_amount numeric(12,2) not null, target_date date, current_amount numeric(12,2) default 0, created_at timestamptz default now() );
alter table profiles enable row level security; alter table categories enable row level security; alter table fixed_bills enable row level security; alter table cards enable row level security; alter table card_purchases enable row level security; alter table cash_flows enable row level security; alter table savings_moves enable row level security; alter table savings_goals enable row level security;
create policy "profiles_self" on profiles for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "categories_owner" on categories for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "fixed_bills_owner" on fixed_bills for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "cards_owner" on cards for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "card_purchases_owner" on card_purchases for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "cash_flows_owner" on cash_flows for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "savings_moves_owner" on savings_moves for all using (user_id = auth.uid()) with check (user_id = auth.uid()); create policy "savings_goals_owner" on savings_goals for all using (user_id = auth.uid()) with check (user_id = auth.uid());
